package org.si.flotaurperatu.probak;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.si.flotaurperatu.interf2.OntzienPanela;
import org.si.flotaurperatu.logic.Egoera;
import org.si.flotaurperatu.logic.Gelaxka;
import org.si.flotaurperatu.logic.TableroIkusi;

public class TableroIkusiTest {
	
	TableroIkusi tablero1;
	OntzienPanela ontziPanela;

	@Before
	public void setUp() throws Exception {
		tablero1 = new TableroIkusi();
		ontziPanela = OntzienPanela.getOntzienPanela();
	}

	@After
	public void tearDown() throws Exception {
		tablero1 = null;
		ontziPanela = null;
	}

	@Test
	public void testKokatu() {
		tablero1.kokatu(0,0);
		Gelaxka gelaxka1 = tablero1.getGelaxka(0,0);
		assertNotNull(gelaxka1);
		assertTrue(gelaxka1.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,1);
		Gelaxka gelaxka2 = tablero1.getGelaxka(0,1);
		assertNotNull(gelaxka2);
		assertTrue(gelaxka2.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,2);
		Gelaxka gelaxka3 = tablero1.getGelaxka(0,2);
		assertNotNull(gelaxka3);
		assertTrue(gelaxka3.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,3);
		Gelaxka gelaxka4 = tablero1.getGelaxka(0,3);
		assertNotNull(gelaxka4);
		assertTrue(gelaxka4.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,4);
		Gelaxka gelaxka5 = tablero1.getGelaxka(0,4);
		assertNotNull(gelaxka5);
		assertTrue(gelaxka5.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,5);
		Gelaxka gelaxka6 = tablero1.getGelaxka(0,5);
		assertNotNull(gelaxka6);
		assertTrue(gelaxka6.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,6);
		Gelaxka gelaxka7 = tablero1.getGelaxka(0,6);
		assertNotNull(gelaxka7);
		assertTrue(gelaxka7.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,7);
		Gelaxka gelaxka8 = tablero1.getGelaxka(0,7);
		assertNotNull(gelaxka8);
		assertTrue(gelaxka8.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,8);
		Gelaxka gelaxka9 = tablero1.getGelaxka(0,8);
		assertNotNull(gelaxka9);
		assertTrue(gelaxka9.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(0,9);
		Gelaxka gelaxka10 = tablero1.getGelaxka(0,9);
		assertNotNull(gelaxka10);
		assertTrue(gelaxka10.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(1,0);
		Gelaxka gelaxka11 = tablero1.getGelaxka(1,0);
		assertNotNull(gelaxka11);
		assertTrue(gelaxka11.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,1);
		Gelaxka gelaxka12 = tablero1.getGelaxka(1,1);
		assertNotNull(gelaxka12);
		assertTrue(gelaxka2.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,2);
		Gelaxka gelaxka13 = tablero1.getGelaxka(1,2);
		assertNotNull(gelaxka13);
		assertTrue(gelaxka13.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,3);
		Gelaxka gelaxka14 = tablero1.getGelaxka(1,3);
		assertNotNull(gelaxka14);
		assertTrue(gelaxka14.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,4);
		Gelaxka gelaxka15 = tablero1.getGelaxka(1,4);
		assertNotNull(gelaxka15);
		assertTrue(gelaxka15.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,5);
		Gelaxka gelaxka16 = tablero1.getGelaxka(1,5);
		assertNotNull(gelaxka16);
		assertTrue(gelaxka16.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,6);
		Gelaxka gelaxka17 = tablero1.getGelaxka(1,6);
		assertNotNull(gelaxka17);
		assertTrue(gelaxka17.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,7);
		Gelaxka gelaxka18 = tablero1.getGelaxka(1,7);
		assertNotNull(gelaxka18);
		assertTrue(gelaxka18.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,8);
		Gelaxka gelaxka19 = tablero1.getGelaxka(1,8);
		assertNotNull(gelaxka19);
		assertTrue(gelaxka19.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(1,9);
		Gelaxka gelaxka20 = tablero1.getGelaxka(1,9);
		assertNotNull(gelaxka20);
		assertTrue(gelaxka20.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(2,0);
		Gelaxka gelaxka21 = tablero1.getGelaxka(2,0);
		assertNotNull(gelaxka21);
		assertTrue(gelaxka21.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,1);
		Gelaxka gelaxka22 = tablero1.getGelaxka(2,1);
		assertNotNull(gelaxka22);
		assertTrue(gelaxka22.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,2);
		Gelaxka gelaxka23 = tablero1.getGelaxka(2,2);
		assertNotNull(gelaxka23);
		assertTrue(gelaxka23.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,3);
		Gelaxka gelaxka24 = tablero1.getGelaxka(2,3);
		assertNotNull(gelaxka24);
		assertTrue(gelaxka24.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,4);
		Gelaxka gelaxka25 = tablero1.getGelaxka(2,4);
		assertNotNull(gelaxka25);
		assertTrue(gelaxka25.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,5);
		Gelaxka gelaxka26 = tablero1.getGelaxka(2,5);
		assertNotNull(gelaxka26);
		assertTrue(gelaxka26.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,6);
		Gelaxka gelaxka27 = tablero1.getGelaxka(2,6);
		assertNotNull(gelaxka27);
		assertTrue(gelaxka27.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,7);
		Gelaxka gelaxka28 = tablero1.getGelaxka(2,7);
		assertNotNull(gelaxka28);
		assertTrue(gelaxka28.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,8);
		Gelaxka gelaxka29 = tablero1.getGelaxka(2,8);
		assertNotNull(gelaxka29);
		assertTrue(gelaxka29.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(2,9);
		Gelaxka gelaxka30 = tablero1.getGelaxka(2,9);
		assertNotNull(gelaxka30);
		assertTrue(gelaxka30.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(3,0);
		Gelaxka gelaxka31 = tablero1.getGelaxka(3,0);
		assertNotNull(gelaxka31);
		assertTrue(gelaxka31.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,1);
		Gelaxka gelaxka32 = tablero1.getGelaxka(3,1);
		assertNotNull(gelaxka32);
		assertTrue(gelaxka22.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,2);
		Gelaxka gelaxka33 = tablero1.getGelaxka(3,2);
		assertNotNull(gelaxka33);
		assertTrue(gelaxka33.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,3);
		Gelaxka gelaxka34 = tablero1.getGelaxka(3,3);
		assertNotNull(gelaxka34);
		assertTrue(gelaxka34.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,4);
		Gelaxka gelaxka35 = tablero1.getGelaxka(3,4);
		assertNotNull(gelaxka35);
		assertTrue(gelaxka35.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,5);
		Gelaxka gelaxka36 = tablero1.getGelaxka(3,5);
		assertNotNull(gelaxka36);
		assertTrue(gelaxka36.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,6);
		Gelaxka gelaxka37 = tablero1.getGelaxka(3,6);
		assertNotNull(gelaxka37);
		assertTrue(gelaxka37.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,7);
		Gelaxka gelaxka38 = tablero1.getGelaxka(3,7);
		assertNotNull(gelaxka38);
		assertTrue(gelaxka28.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,8);
		Gelaxka gelaxka39 = tablero1.getGelaxka(3,8);
		assertNotNull(gelaxka39);
		assertTrue(gelaxka29.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(3,9);
		Gelaxka gelaxka40 = tablero1.getGelaxka(3,9);
		assertNotNull(gelaxka40);
		assertTrue(gelaxka40.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(4,0);
		Gelaxka gelaxka41 = tablero1.getGelaxka(4,0);
		assertNotNull(gelaxka41);
		assertTrue(gelaxka41.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,1);
		Gelaxka gelaxka42 = tablero1.getGelaxka(4,1);
		assertNotNull(gelaxka42);
		assertTrue(gelaxka42.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,2);
		Gelaxka gelaxka43 = tablero1.getGelaxka(4,2);
		assertNotNull(gelaxka43);
		assertTrue(gelaxka43.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,3);
		Gelaxka gelaxka44 = tablero1.getGelaxka(4,3);
		assertNotNull(gelaxka44);
		assertTrue(gelaxka44.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,4);
		Gelaxka gelaxka45 = tablero1.getGelaxka(4,4);
		assertNotNull(gelaxka45);
		assertTrue(gelaxka45.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,5);
		Gelaxka gelaxka46 = tablero1.getGelaxka(4,5);
		assertNotNull(gelaxka46);
		assertTrue(gelaxka46.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,6);
		Gelaxka gelaxka47 = tablero1.getGelaxka(4,6);
		assertNotNull(gelaxka47);
		assertTrue(gelaxka47.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,7);
		Gelaxka gelaxka48 = tablero1.getGelaxka(4,7);
		assertNotNull(gelaxka48);
		assertTrue(gelaxka48.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,8);
		Gelaxka gelaxka49 = tablero1.getGelaxka(4,8);
		assertNotNull(gelaxka49);
		assertTrue(gelaxka49.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(4,9);
		Gelaxka gelaxka50 = tablero1.getGelaxka(4,9);
		assertNotNull(gelaxka50);
		assertTrue(gelaxka50.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(5,0);
		Gelaxka gelaxka51 = tablero1.getGelaxka(5,0);
		assertNotNull(gelaxka51);
		assertTrue(gelaxka51.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,1);
		Gelaxka gelaxka52 = tablero1.getGelaxka(5,1);
		assertNotNull(gelaxka52);
		assertTrue(gelaxka52.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,2);
		Gelaxka gelaxka53 = tablero1.getGelaxka(5,2);
		assertNotNull(gelaxka53);
		assertTrue(gelaxka53.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,3);
		Gelaxka gelaxka54 = tablero1.getGelaxka(5,3);
		assertNotNull(gelaxka54);
		assertTrue(gelaxka54.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,4);
		Gelaxka gelaxka55 = tablero1.getGelaxka(5,4);
		assertNotNull(gelaxka55);
		assertTrue(gelaxka55.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,5);
		Gelaxka gelaxka56 = tablero1.getGelaxka(5,5);
		assertNotNull(gelaxka56);
		assertTrue(gelaxka56.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,6);
		Gelaxka gelaxka57 = tablero1.getGelaxka(5,6);
		assertNotNull(gelaxka57);
		assertTrue(gelaxka57.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,7);
		Gelaxka gelaxka58 = tablero1.getGelaxka(5,7);
		assertNotNull(gelaxka58);
		assertTrue(gelaxka58.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,8);
		Gelaxka gelaxka59 = tablero1.getGelaxka(5,8);
		assertNotNull(gelaxka59);
		assertTrue(gelaxka59.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(5,9);
		Gelaxka gelaxka60 = tablero1.getGelaxka(5,9);
		assertNotNull(gelaxka60);
		assertTrue(gelaxka60.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(6,0);
		Gelaxka gelaxka61 = tablero1.getGelaxka(6,0);
		assertNotNull(gelaxka61);
		assertTrue(gelaxka61.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,1);
		Gelaxka gelaxka62 = tablero1.getGelaxka(6,1);
		assertNotNull(gelaxka62);
		assertTrue(gelaxka62.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,2);
		Gelaxka gelaxka63 = tablero1.getGelaxka(6,2);
		assertNotNull(gelaxka63);
		assertTrue(gelaxka63.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,3);
		Gelaxka gelaxka64 = tablero1.getGelaxka(6,3);
		assertNotNull(gelaxka64);
		assertTrue(gelaxka64.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,4);
		Gelaxka gelaxka65 = tablero1.getGelaxka(6,4);
		assertNotNull(gelaxka65);
		assertTrue(gelaxka65.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,5);
		Gelaxka gelaxka66 = tablero1.getGelaxka(6,5);
		assertNotNull(gelaxka66);
		assertTrue(gelaxka66.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,6);
		Gelaxka gelaxka67 = tablero1.getGelaxka(6,6);
		assertNotNull(gelaxka67);
		assertTrue(gelaxka67.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,7);
		Gelaxka gelaxka68 = tablero1.getGelaxka(6,7);
		assertNotNull(gelaxka68);
		assertTrue(gelaxka68.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,8);
		Gelaxka gelaxka69 = tablero1.getGelaxka(6,8);
		assertNotNull(gelaxka69);
		assertTrue(gelaxka69.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(6,9);
		Gelaxka gelaxka70 = tablero1.getGelaxka(6,9);
		assertNotNull(gelaxka70);
		assertTrue(gelaxka70.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(7,0);
		Gelaxka gelaxka71 = tablero1.getGelaxka(7,0);
		assertNotNull(gelaxka71);
		assertTrue(gelaxka71.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,1);
		Gelaxka gelaxka72 = tablero1.getGelaxka(7,1);
		assertNotNull(gelaxka72);
		assertTrue(gelaxka72.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,2);
		Gelaxka gelaxka73 = tablero1.getGelaxka(7,2);
		assertNotNull(gelaxka73);
		assertTrue(gelaxka73.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,3);
		Gelaxka gelaxka74 = tablero1.getGelaxka(7,3);
		assertNotNull(gelaxka74);
		assertTrue(gelaxka74.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,4);
		Gelaxka gelaxka75 = tablero1.getGelaxka(7,4);
		assertNotNull(gelaxka75);
		assertTrue(gelaxka75.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,5);
		Gelaxka gelaxka76 = tablero1.getGelaxka(7,5);
		assertNotNull(gelaxka76);
		assertTrue(gelaxka76.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,6);
		Gelaxka gelaxka77 = tablero1.getGelaxka(7,6);
		assertNotNull(gelaxka77);
		assertTrue(gelaxka77.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,7);
		Gelaxka gelaxka78 = tablero1.getGelaxka(7,7);
		assertNotNull(gelaxka78);
		assertTrue(gelaxka78.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,8);
		Gelaxka gelaxka79 = tablero1.getGelaxka(7,8);
		assertNotNull(gelaxka79);
		assertTrue(gelaxka79.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(7,9);
		Gelaxka gelaxka80 = tablero1.getGelaxka(7,9);
		assertNotNull(gelaxka80);
		assertTrue(gelaxka80.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(8,0);
		Gelaxka gelaxka81 = tablero1.getGelaxka(8,0);
		assertNotNull(gelaxka81);
		assertTrue(gelaxka81.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,1);
		Gelaxka gelaxka82 = tablero1.getGelaxka(8,1);
		assertNotNull(gelaxka82);
		assertTrue(gelaxka82.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,2);
		Gelaxka gelaxka83 = tablero1.getGelaxka(8,2);
		assertNotNull(gelaxka83);
		assertTrue(gelaxka83.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,3);
		Gelaxka gelaxka84 = tablero1.getGelaxka(8,3);
		assertNotNull(gelaxka84);
		assertTrue(gelaxka84.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,4);
		Gelaxka gelaxka85 = tablero1.getGelaxka(8,4);
		assertNotNull(gelaxka85);
		assertTrue(gelaxka85.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,5);
		Gelaxka gelaxka86 = tablero1.getGelaxka(8,5);
		assertNotNull(gelaxka86);
		assertTrue(gelaxka86.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,6);
		Gelaxka gelaxka87 = tablero1.getGelaxka(8,6);
		assertNotNull(gelaxka87);
		assertTrue(gelaxka87.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,7);
		Gelaxka gelaxka88 = tablero1.getGelaxka(8,7);
		assertNotNull(gelaxka88);
		assertTrue(gelaxka88.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,8);
		Gelaxka gelaxka89 = tablero1.getGelaxka(8,8);
		assertNotNull(gelaxka89);
		assertTrue(gelaxka89.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(8,9);
		Gelaxka gelaxka90 = tablero1.getGelaxka(8,9);
		assertNotNull(gelaxka90);
		assertTrue(gelaxka90.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(9,0);
		Gelaxka gelaxka91 = tablero1.getGelaxka(9,0);
		assertNotNull(gelaxka91);
		assertTrue(gelaxka91.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,1);
		Gelaxka gelaxka92 = tablero1.getGelaxka(9,1);
		assertNotNull(gelaxka92);
		assertTrue(gelaxka92.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,2);
		Gelaxka gelaxka93 = tablero1.getGelaxka(9,2);
		assertNotNull(gelaxka93);
		assertTrue(gelaxka93.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,3);
		Gelaxka gelaxka94 = tablero1.getGelaxka(9,3);
		assertNotNull(gelaxka94);
		assertTrue(gelaxka94.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,4);
		Gelaxka gelaxka95 = tablero1.getGelaxka(9,4);
		assertNotNull(gelaxka95);
		assertTrue(gelaxka95.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,5);
		Gelaxka gelaxka96 = tablero1.getGelaxka(9,5);
		assertNotNull(gelaxka96);
		assertTrue(gelaxka96.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,6);
		Gelaxka gelaxka97 = tablero1.getGelaxka(9,6);
		assertNotNull(gelaxka97);
		assertTrue(gelaxka97.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,7);
		Gelaxka gelaxka98 = tablero1.getGelaxka(9,7);
		assertNotNull(gelaxka98);
		assertTrue(gelaxka98.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,8);
		Gelaxka gelaxka99 = tablero1.getGelaxka(9,8);
		assertNotNull(gelaxka99);
		assertTrue(gelaxka99.getEgoera().equals(Egoera.ONTZIA));
		tablero1.kokatu(9,9);
		Gelaxka gelaxka100 = tablero1.getGelaxka(9,9);
		assertNotNull(gelaxka100);
		assertTrue(gelaxka100.getEgoera().equals(Egoera.ONTZIA));
		
		tablero1.kokatu(10,10);
		Gelaxka gelaxka = tablero1.getGelaxka(10,10);
		assertNull(gelaxka);
	}

	@Test
	public void testGetGelaxka() {
		Gelaxka gelaxka1 = tablero1.getGelaxka(0,0);
		assertNotNull(gelaxka1);
		Gelaxka gelaxka2 = tablero1.getGelaxka(0,1);
		assertNotNull(gelaxka2);
		Gelaxka gelaxka3 = tablero1.getGelaxka(0,2);
		assertNotNull(gelaxka3);
		Gelaxka gelaxka4 = tablero1.getGelaxka(0,3);
		assertNotNull(gelaxka4);
		Gelaxka gelaxka5 = tablero1.getGelaxka(0,4);
		assertNotNull(gelaxka5);
		Gelaxka gelaxka6 = tablero1.getGelaxka(0,5);
		assertNotNull(gelaxka6);
		Gelaxka gelaxka7 = tablero1.getGelaxka(0,6);
		assertNotNull(gelaxka7);
		Gelaxka gelaxka8 = tablero1.getGelaxka(0,7);
		assertNotNull(gelaxka8);
		Gelaxka gelaxka9 = tablero1.getGelaxka(0,8);
		assertNotNull(gelaxka9);
		Gelaxka gelaxka10 = tablero1.getGelaxka(0,9);
		assertNotNull(gelaxka10);
		
		Gelaxka gelaxka11 = tablero1.getGelaxka(1,0);
		assertNotNull(gelaxka11);
		Gelaxka gelaxka12 = tablero1.getGelaxka(1,1);
		assertNotNull(gelaxka12);
		Gelaxka gelaxka13 = tablero1.getGelaxka(1,2);
		assertNotNull(gelaxka13);
		Gelaxka gelaxka14 = tablero1.getGelaxka(1,3);
		assertNotNull(gelaxka14);
		Gelaxka gelaxka15 = tablero1.getGelaxka(1,4);
		assertNotNull(gelaxka15);
		Gelaxka gelaxka16 = tablero1.getGelaxka(1,5);
		assertNotNull(gelaxka16);
		Gelaxka gelaxka17 = tablero1.getGelaxka(1,6);
		assertNotNull(gelaxka17);
		Gelaxka gelaxka18 = tablero1.getGelaxka(1,7);
		assertNotNull(gelaxka18);
		Gelaxka gelaxka19 = tablero1.getGelaxka(1,8);
		assertNotNull(gelaxka19);
		Gelaxka gelaxka20 = tablero1.getGelaxka(1,9);
		assertNotNull(gelaxka20);
		
		Gelaxka gelaxka21 = tablero1.getGelaxka(2,0);
		assertNotNull(gelaxka21);
		Gelaxka gelaxka22 = tablero1.getGelaxka(2,1);
		assertNotNull(gelaxka22);
		Gelaxka gelaxka23 = tablero1.getGelaxka(2,2);
		assertNotNull(gelaxka23);
		Gelaxka gelaxka24 = tablero1.getGelaxka(2,3);
		assertNotNull(gelaxka24);
		Gelaxka gelaxka25 = tablero1.getGelaxka(2,4);
		assertNotNull(gelaxka25);
		Gelaxka gelaxka26 = tablero1.getGelaxka(2,5);
		assertNotNull(gelaxka26);
		Gelaxka gelaxka27 = tablero1.getGelaxka(2,6);
		assertNotNull(gelaxka27);
		Gelaxka gelaxka28 = tablero1.getGelaxka(2,7);
		assertNotNull(gelaxka28);
		Gelaxka gelaxka29 = tablero1.getGelaxka(2,8);
		assertNotNull(gelaxka29);
		Gelaxka gelaxka30 = tablero1.getGelaxka(2,9);
		assertNotNull(gelaxka30);
		
		Gelaxka gelaxka31 = tablero1.getGelaxka(3,0);
		assertNotNull(gelaxka31);
		Gelaxka gelaxka32 = tablero1.getGelaxka(3,1);
		assertNotNull(gelaxka32);
		Gelaxka gelaxka33 = tablero1.getGelaxka(3,2);
		assertNotNull(gelaxka33);
		Gelaxka gelaxka34 = tablero1.getGelaxka(3,3);
		assertNotNull(gelaxka34);
		Gelaxka gelaxka35 = tablero1.getGelaxka(3,4);
		assertNotNull(gelaxka35);
		Gelaxka gelaxka36 = tablero1.getGelaxka(3,5);
		assertNotNull(gelaxka36);
		Gelaxka gelaxka37 = tablero1.getGelaxka(3,6);
		assertNotNull(gelaxka37);
		Gelaxka gelaxka38 = tablero1.getGelaxka(3,7);
		assertNotNull(gelaxka38);
		Gelaxka gelaxka39 = tablero1.getGelaxka(3,8);
		assertNotNull(gelaxka39);
		Gelaxka gelaxka40 = tablero1.getGelaxka(3,9);
		assertNotNull(gelaxka40);
		
		Gelaxka gelaxka41 = tablero1.getGelaxka(4,0);
		assertNotNull(gelaxka41);
		Gelaxka gelaxka42 = tablero1.getGelaxka(4,1);
		assertNotNull(gelaxka42);
		Gelaxka gelaxka43 = tablero1.getGelaxka(4,2);
		assertNotNull(gelaxka43);
		Gelaxka gelaxka44 = tablero1.getGelaxka(4,3);
		assertNotNull(gelaxka44);
		Gelaxka gelaxka45 = tablero1.getGelaxka(4,4);
		assertNotNull(gelaxka45);
		Gelaxka gelaxka46 = tablero1.getGelaxka(4,5);
		assertNotNull(gelaxka46);
		Gelaxka gelaxka47 = tablero1.getGelaxka(4,6);
		assertNotNull(gelaxka47);
		Gelaxka gelaxka48 = tablero1.getGelaxka(4,7);
		assertNotNull(gelaxka48);
		Gelaxka gelaxka49 = tablero1.getGelaxka(4,8);
		assertNotNull(gelaxka49);
		Gelaxka gelaxka50 = tablero1.getGelaxka(4,9);
		assertNotNull(gelaxka50);
		
		Gelaxka gelaxka51 = tablero1.getGelaxka(5,0);
		assertNotNull(gelaxka51);
		Gelaxka gelaxka52 = tablero1.getGelaxka(5,1);
		assertNotNull(gelaxka52);
		Gelaxka gelaxka53 = tablero1.getGelaxka(5,2);
		assertNotNull(gelaxka53);
		Gelaxka gelaxka54 = tablero1.getGelaxka(5,3);
		assertNotNull(gelaxka54);
		Gelaxka gelaxka55 = tablero1.getGelaxka(5,4);
		assertNotNull(gelaxka55);
		Gelaxka gelaxka56 = tablero1.getGelaxka(5,5);
		assertNotNull(gelaxka56);
		Gelaxka gelaxka57 = tablero1.getGelaxka(5,6);
		assertNotNull(gelaxka57);
		Gelaxka gelaxka58 = tablero1.getGelaxka(5,7);
		assertNotNull(gelaxka58);
		Gelaxka gelaxka59 = tablero1.getGelaxka(5,8);
		assertNotNull(gelaxka59);
		Gelaxka gelaxka60 = tablero1.getGelaxka(5,9);
		assertNotNull(gelaxka60);
		
		Gelaxka gelaxka61 = tablero1.getGelaxka(6,0);
		assertNotNull(gelaxka61);
		Gelaxka gelaxka62 = tablero1.getGelaxka(6,1);
		assertNotNull(gelaxka62);
		Gelaxka gelaxka63 = tablero1.getGelaxka(6,2);
		assertNotNull(gelaxka63);
		Gelaxka gelaxka64 = tablero1.getGelaxka(6,3);
		assertNotNull(gelaxka64);
		Gelaxka gelaxka65 = tablero1.getGelaxka(6,4);
		assertNotNull(gelaxka65);
		Gelaxka gelaxka66 = tablero1.getGelaxka(6,5);
		assertNotNull(gelaxka66);
		Gelaxka gelaxka67 = tablero1.getGelaxka(6,6);
		assertNotNull(gelaxka67);
		Gelaxka gelaxka68 = tablero1.getGelaxka(6,7);
		assertNotNull(gelaxka68);
		Gelaxka gelaxka69 = tablero1.getGelaxka(6,8);
		assertNotNull(gelaxka69);
		Gelaxka gelaxka70 = tablero1.getGelaxka(6,9);
		assertNotNull(gelaxka70);
		
		Gelaxka gelaxka71 = tablero1.getGelaxka(7,0);
		assertNotNull(gelaxka71);
		Gelaxka gelaxka72 = tablero1.getGelaxka(7,1);
		assertNotNull(gelaxka72);
		Gelaxka gelaxka73 = tablero1.getGelaxka(7,2);
		assertNotNull(gelaxka73);
		Gelaxka gelaxka74 = tablero1.getGelaxka(7,3);
		assertNotNull(gelaxka74);
		Gelaxka gelaxka75 = tablero1.getGelaxka(7,4);
		assertNotNull(gelaxka75);
		Gelaxka gelaxka76 = tablero1.getGelaxka(7,5);
		assertNotNull(gelaxka76);
		Gelaxka gelaxka77 = tablero1.getGelaxka(7,6);
		assertNotNull(gelaxka77);
		Gelaxka gelaxka78 = tablero1.getGelaxka(7,7);
		assertNotNull(gelaxka78);
		Gelaxka gelaxka79 = tablero1.getGelaxka(7,8);
		assertNotNull(gelaxka79);
		Gelaxka gelaxka80 = tablero1.getGelaxka(7,9);
		assertNotNull(gelaxka80);
		
		Gelaxka gelaxka81 = tablero1.getGelaxka(8,0);
		assertNotNull(gelaxka81);
		Gelaxka gelaxka82 = tablero1.getGelaxka(8,1);
		assertNotNull(gelaxka82);
		Gelaxka gelaxka83 = tablero1.getGelaxka(8,2);
		assertNotNull(gelaxka83);
		Gelaxka gelaxka84 = tablero1.getGelaxka(8,3);
		assertNotNull(gelaxka84);
		Gelaxka gelaxka85 = tablero1.getGelaxka(8,4);
		assertNotNull(gelaxka85);
		Gelaxka gelaxka86 = tablero1.getGelaxka(8,5);
		assertNotNull(gelaxka86);
		Gelaxka gelaxka87 = tablero1.getGelaxka(8,6);
		assertNotNull(gelaxka87);
		Gelaxka gelaxka88 = tablero1.getGelaxka(8,7);
		assertNotNull(gelaxka88);
		Gelaxka gelaxka89 = tablero1.getGelaxka(8,8);
		assertNotNull(gelaxka89);
		Gelaxka gelaxka90 = tablero1.getGelaxka(8,9);
		assertNotNull(gelaxka90);
		
		Gelaxka gelaxka91 = tablero1.getGelaxka(9,0);
		assertNotNull(gelaxka91);
		Gelaxka gelaxka92 = tablero1.getGelaxka(9,1);
		assertNotNull(gelaxka92);
		Gelaxka gelaxka93 = tablero1.getGelaxka(9,2);
		assertNotNull(gelaxka93);
		Gelaxka gelaxka94 = tablero1.getGelaxka(9,3);
		assertNotNull(gelaxka94);
		Gelaxka gelaxka95 = tablero1.getGelaxka(9,4);
		assertNotNull(gelaxka95);
		Gelaxka gelaxka96 = tablero1.getGelaxka(9,5);
		assertNotNull(gelaxka96);
		Gelaxka gelaxka97 = tablero1.getGelaxka(9,6);
		assertNotNull(gelaxka97);
		Gelaxka gelaxka98 = tablero1.getGelaxka(9,7);
		assertNotNull(gelaxka98);
		Gelaxka gelaxka99 = tablero1.getGelaxka(9,8);
		assertNotNull(gelaxka99);
		Gelaxka gelaxka100 = tablero1.getGelaxka(9,9);
		assertNotNull(gelaxka100);
		
		Gelaxka gelaxka= tablero1.getGelaxka(10,10);
		assertNull(gelaxka);
	}

	@Test
	public void testKonprobatu() {
		assertTrue(true);
	}

	@Test
	public void testKonprobatuKasila() {
		assertTrue(tablero1.konprobatuKasila(0,0));
		assertTrue(tablero1.konprobatuKasila(0,1));
		assertTrue(tablero1.konprobatuKasila(0,2));
		assertTrue(tablero1.konprobatuKasila(0,3));
		assertTrue(tablero1.konprobatuKasila(0,4));
		assertTrue(tablero1.konprobatuKasila(0,5));
		assertTrue(tablero1.konprobatuKasila(0,6));
		assertTrue(tablero1.konprobatuKasila(0,7));
		assertTrue(tablero1.konprobatuKasila(0,8));
		assertTrue(tablero1.konprobatuKasila(0,9));
		assertTrue(tablero1.konprobatuKasila(1,0));
		assertTrue(tablero1.konprobatuKasila(1,1));
		assertTrue(tablero1.konprobatuKasila(1,2));
		assertTrue(tablero1.konprobatuKasila(1,3));
		assertTrue(tablero1.konprobatuKasila(1,4));
		assertTrue(tablero1.konprobatuKasila(1,5));
		assertTrue(tablero1.konprobatuKasila(1,6));
		assertTrue(tablero1.konprobatuKasila(1,7));
		assertTrue(tablero1.konprobatuKasila(1,8));
		assertTrue(tablero1.konprobatuKasila(1,9));
		assertTrue(tablero1.konprobatuKasila(2,0));
		assertTrue(tablero1.konprobatuKasila(2,1));
		assertTrue(tablero1.konprobatuKasila(2,2));
		assertTrue(tablero1.konprobatuKasila(2,3));
		assertTrue(tablero1.konprobatuKasila(2,4));
		assertTrue(tablero1.konprobatuKasila(2,5));
		assertTrue(tablero1.konprobatuKasila(2,6));
		assertTrue(tablero1.konprobatuKasila(2,7));
		assertTrue(tablero1.konprobatuKasila(2,8));
		assertTrue(tablero1.konprobatuKasila(2,9));
		assertTrue(tablero1.konprobatuKasila(3,0));
		assertTrue(tablero1.konprobatuKasila(3,1));
		assertTrue(tablero1.konprobatuKasila(3,2));
		assertTrue(tablero1.konprobatuKasila(3,3));
		assertTrue(tablero1.konprobatuKasila(3,4));
		assertTrue(tablero1.konprobatuKasila(3,5));
		assertTrue(tablero1.konprobatuKasila(3,6));
		assertTrue(tablero1.konprobatuKasila(3,7));
		assertTrue(tablero1.konprobatuKasila(3,8));
		assertTrue(tablero1.konprobatuKasila(3,9));
		assertTrue(tablero1.konprobatuKasila(4,0));
		assertTrue(tablero1.konprobatuKasila(4,1));
		assertTrue(tablero1.konprobatuKasila(4,2));
		assertTrue(tablero1.konprobatuKasila(4,3));
		assertTrue(tablero1.konprobatuKasila(4,4));
		assertTrue(tablero1.konprobatuKasila(4,5));
		assertTrue(tablero1.konprobatuKasila(4,6));
		assertTrue(tablero1.konprobatuKasila(4,7));
		assertTrue(tablero1.konprobatuKasila(4,8));
		assertTrue(tablero1.konprobatuKasila(4,9));
		assertTrue(tablero1.konprobatuKasila(5,0));
		assertTrue(tablero1.konprobatuKasila(5,1));
		assertTrue(tablero1.konprobatuKasila(5,2));
		assertTrue(tablero1.konprobatuKasila(5,3));
		assertTrue(tablero1.konprobatuKasila(5,4));
		assertTrue(tablero1.konprobatuKasila(5,5));
		assertTrue(tablero1.konprobatuKasila(5,6));
		assertTrue(tablero1.konprobatuKasila(5,7));
		assertTrue(tablero1.konprobatuKasila(5,8));
		assertTrue(tablero1.konprobatuKasila(5,9));
		assertTrue(tablero1.konprobatuKasila(6,0));
		assertTrue(tablero1.konprobatuKasila(6,1));
		assertTrue(tablero1.konprobatuKasila(6,2));
		assertTrue(tablero1.konprobatuKasila(6,3));
		assertTrue(tablero1.konprobatuKasila(6,4));
		assertTrue(tablero1.konprobatuKasila(6,5));
		assertTrue(tablero1.konprobatuKasila(6,6));
		assertTrue(tablero1.konprobatuKasila(6,7));
		assertTrue(tablero1.konprobatuKasila(6,8));
		assertTrue(tablero1.konprobatuKasila(6,9));
		assertTrue(tablero1.konprobatuKasila(7,0));
		assertTrue(tablero1.konprobatuKasila(7,1));
		assertTrue(tablero1.konprobatuKasila(7,2));
		assertTrue(tablero1.konprobatuKasila(7,3));
		assertTrue(tablero1.konprobatuKasila(7,4));
		assertTrue(tablero1.konprobatuKasila(7,5));
		assertTrue(tablero1.konprobatuKasila(7,6));
		assertTrue(tablero1.konprobatuKasila(7,7));
		assertTrue(tablero1.konprobatuKasila(7,8));
		assertTrue(tablero1.konprobatuKasila(7,9));
		assertTrue(tablero1.konprobatuKasila(8,0));
		assertTrue(tablero1.konprobatuKasila(8,1));
		assertTrue(tablero1.konprobatuKasila(8,2));
		assertTrue(tablero1.konprobatuKasila(8,3));
		assertTrue(tablero1.konprobatuKasila(8,4));
		assertTrue(tablero1.konprobatuKasila(8,5));
		assertTrue(tablero1.konprobatuKasila(8,6));
		assertTrue(tablero1.konprobatuKasila(8,7));
		assertTrue(tablero1.konprobatuKasila(8,8));
		assertTrue(tablero1.konprobatuKasila(8,9));
		assertTrue(tablero1.konprobatuKasila(9,0));
		assertTrue(tablero1.konprobatuKasila(9,1));
		assertTrue(tablero1.konprobatuKasila(9,2));
		assertTrue(tablero1.konprobatuKasila(9,3));
		assertTrue(tablero1.konprobatuKasila(9,4));
		assertTrue(tablero1.konprobatuKasila(9,5));
		assertTrue(tablero1.konprobatuKasila(9,6));
		assertTrue(tablero1.konprobatuKasila(9,7));
		assertTrue(tablero1.konprobatuKasila(9,8));
		assertTrue(tablero1.konprobatuKasila(9,9));
	}

}
